export default {
  GET_POKEMON_REQUESTED: 'GET_POKEMON_REQUESTED',
  GET_POKEMON_SUCCEEDED: 'GET_POKEMON_SUCCEEDED',
  GET_POKEMON_FAILED: 'GET_POKEMON_FAILED',
  GET_POKEMONS_REQUESTED: 'GET_POKEMONS_REQUESTED',
  GET_POKEMONS_SUCCEEDED: 'GET_POKEMONS_SUCCEEDED',
  GET_POKEMONS_FAILED: 'GET_POKEMONS_FAILED',
}